### ISSUE TITLE
Delayed movement after landing

### ISSUE THREAD

**Issue by james5922** [HouraiTeahouse/FantasyCrescendo#158] opened 2017-06-24 14:01 UTC
- Fantasy Crescendo Version: Build **265**
- Operating System: Windows 7
- Expected Behavior: Immediate ability to move after landing
- Actual Behavior: Delay of about 1 second between landing and regaining movement.
- Steps to reproduce the behavior:
  1: Select the "Forest of Magic" stage.
  2: Jump. Doesn't matter which kind of jump.
  3: Try to move immediately after landing.

[output_log.txt](https://github.com/HouraiTeahouse/FantasyCrescendo/files/1099814/output_log.txt)

**Comment by pzhang87** [comment] 2017-06-24 18:43
Seems like this is working as intended but the landing lag time window is much too large.

**Comment by james5922** [comment] 2017-06-24 19:02
I was getting 25 FPS at the time, if that helps with anything.

**Comment by james7132** [comment] 2017-06-25 03:47
@pzhang87 what is a good timing relative to what we see now.

@james5922: animations should be framerate independent. Framerate shouldn't affect the actual timing.

**Comment by james5922** [comment] 2017-07-11 14:49
Bug still occurs in Build 265.

**Comment by james7132** [comment] 2017-07-12 19:36
As discussed on Discord, this seems to be resolved. Closing.

**Closed by james7132** 2017-07-12 19:36 UTC
Labels: Category:Animation, Category:Game Engine, Priority:2, Severity:1, Status:Assigned, Type:Bug
