### ISSUE TITLE
local server host is extremely buggy

### ISSUE THREAD

**Issue by HanedTom** [HouraiTeahouse/FantasyCrescendo#78] opened 2017-03-13 01:32 UTC
when toggled once it will turn the spawn platforms to a visible state and when you make a local game
![screenshot-03-13-2017-012454](https://cloud.githubusercontent.com/assets/25497816/23838312/66997e02-0762-11e7-9f69-6d5a3035d0bc.png)
Toggling it again after you move youmu and leave the game will cause a spawn platform to show up at her last position with respect to her feet
 ![screenshot-03-13-2017-012637](https://cloud.githubusercontent.com/assets/25497816/23838342/abb3cca4-0762-11e7-8a11-c79324e878d7.png)
and spamming it and joining will either erase youmu or well double her
![screenshot-03-13-2017-012803](https://cloud.githubusercontent.com/assets/25497816/23838362/e65067f0-0762-11e7-838c-905fe86f8d5f.png)
as well as the double still existing as you leave the host. 
![screenshot-03-13-2017-012923](https://cloud.githubusercontent.com/assets/25497816/23838377/02de21a0-0763-11e7-80b7-92fd434b1fba.png)

**Comment by james7132** [comment] 2017-03-15 08:52
I am unable to replicate this bug in the latest build. Can you retry this on the latest test build and see if you are still able to recreate it?

**Comment by james7132** [comment] 2017-03-17 02:10
Able to replicate. This seems to be caused by a bug with Unity's networking implementation: https://issuetracker.unity3d.com/issues/unet-onstartserver-and-onstartclient-are-not-called-as-host-if-they-were-used-in-a-previous-session-as-client

**Comment by james7132** [comment] 2017-03-17 02:12
As this bug is a result of the testing environment we are using rather than the base level work towards the game, I'm closing this bug as this likely will not be present in the end product. If this persists in the public demo, we can reopen it.

**Closed by james7132** 2017-03-17 02:12 UTC
Labels: bug, game-engine
